# Generated by Django 5.1.7 on 2026-04-04 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, help_text='QuickBooks Client ID', max_length=255)),
                ('client_secret', models.CharField(blank=True, help_text='QuickBooks Client Secret', max_length=255)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('redirect_uri', models.URLField(blank=True, help_text='OAuth Redirect URI', max_length=255)),
                ('realm_id', models.CharField(blank=True, help_text='Company ID (Realm ID)', max_length=64)),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth Refresh Token')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'QuickBooks Configuration',
                'verbose_name_plural': 'QuickBooks Configurations',
            },
        ),
    ]
