# Generated by Django 5.1.7 on 2026-04-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_gateway', '0002_quickbooksconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickbooksconfig',
            name='webhook_token',
            field=models.CharField(blank=True, help_text='Webhook Verifier Token', max_length=255),
        ),
    ]
