# Generated by Django 5.1.7 on 2026-04-04 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcp_gateway', '0003_quickbooksconfig_webhook_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuickBooksConfig',
        ),
    ]
