# Generated by Django 5.1.7 on 2026-03-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sheet_tag', models.CharField(blank=True, help_text='Google Sheets customer tag', max_length=255)),
                ('remark', models.TextField(blank=True)),
                ('important', models.BooleanField(default=False)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', 'name'],
            },
        ),
    ]
