# Generated by Django 5.1.7 on 2026-03-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_customer_city_customer_company_name_customer_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('retail', 'Retail Customer'), ('school', 'School'), ('partner', 'Partner'), ('other', 'Other')], help_text='Type/class of customer', max_length=32),
        ),
    ]
