# Generated by Django 5.1.7 on 2026-03-30 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_add_lat_lng'),
        ('crm', '0003_customer_customer_type'),
    ]

    operations = [
    ]
