# Generated by Django 5.1.7 on 2026-03-30 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_type_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customertype',
            options={'ordering': ['key']},
        ),
    ]
