# Generated by Django 5.1.7 on 2026-03-31 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_customertype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.TextField(blank=True, help_text='Customer profile / description'),
        ),
        migrations.AddField(
            model_name='customer',
            name='website_url',
            field=models.URLField(blank=True, help_text='Customer website or URL'),
        ),
    ]
