# Generated by patch: add attn and fax fields to Customer
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_customer_profile_customer_website_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="attn",
            field=models.CharField(max_length=255, blank=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="fax",
            field=models.CharField(max_length=64, blank=True),
        ),
    ]
