# Generated by Django 5.1.7 on 2026-04-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_add_attn_fax'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='attn_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='attn_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_2',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_3',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_3',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
