# Generated by Django 5.1.7 on 2026-04-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_add_extra_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='in_quickbooks',
            field=models.BooleanField(default=False, help_text='Indicates if this customer is synced with QuickBooks'),
        ),
        migrations.AddField(
            model_name='customer',
            name='quickbooks_id',
            field=models.CharField(blank=True, db_index=True, help_text='QuickBooks Customer ID', max_length=64),
        ),
    ]
