# Generated by Django 5.1.7 on 2026-04-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(blank=True, help_text='Raw payload body')),
                ('signature', models.CharField(blank=True, help_text='Intuit Signature', max_length=255)),
                ('is_verified', models.BooleanField(default=False, help_text='Signature verified successfully')),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
