# Generated by Django 5.1.7 on 2026-04-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qb_integration', '0002_quickbookswebhooklog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickBooksAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('url', models.URLField(blank=True, max_length=1024)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('request_body', models.TextField(blank=True, help_text='Request Payload')),
                ('response_body', models.TextField(blank=True, help_text='Response Payload')),
                ('success', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
